### ISSUE TITLE
a task list item

### ISSUE THREAD

**Issue by edagarli** [edagarli/bugs#3]
a task list item

**Comment by edagarli** [comment]
#3

**Comment by edagarli** [comment]
- [x] a task list item  #4 
- [x] list syntax required
- [x] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [x] completed

**Comment by edagarli** [comment]
interesting
